### PR TITLE
CoffeeScript: Show styles of generating markup

### PR DESCRIPTION
**Pull request by wmertens**
Provide some examples of how to write react calls in plain CoffeeScript

### CODE REVIEW

**Comment by taiansu** [comment]
The thing is JSX actually improves the readability, even in the CoffeeScript/LiveScript, IMHO.
That's the reason I put the cjsx-loader in, to enable, and also encourage people to write the JSX syntax in CoffeeScript/LiveScript.

**Comment by wmertens** [comment]
I really like being able to call functions and generate arrays in
coffeescript for loops, which is why I prefer plain syntax. Basically I
wanted people to see all the available options...

**Comment by taiansu** [comment]
If I merge your pr, then people can't see the available options of using JSX syntax. For people who don't like JSX, they can't just simply remove it. There already official document in React (javascript) and also couple blog post tutorial (coffee-script/Livescript) for not using JSX, but fewer information for another side.

**Comment by wmertens** [comment]
It's your project, I understand, no hard feelings :smile:.

**Comment by taiansu** [comment]
:D

**Pull request closed without merging**
